dev-team-study/algorithm-study

- src/main/java/tommy/BOJ_3085.java
- Brute Force 
- 문제를 분석해 본 결과 가로 세로 모두 각자 검색을 해야 한다는 판단을 내림
- 문제의 복잡도를 낮추기 위해 세로 Switching, 가로 Switching을 별도로 실시 
- search의 경우에도 가로 검색, 세로 검색 별도로 실시 
- 문자가 다를 경우 다시 시작해야하므로 count 1로 초기화 
---
> 처음에 접근 시에 모든 행들을 순회해야한다는 생각은 했으나, Switching까지 한다면 복잡도가 너무 올라가서 안되지 않을까 하고 머리를 싸매다가 결국에는 다른 분의 코드를 조금 참고했습니다.  
> 문제를 다시 확인해보니 비록 복잡도가 O(N^4) 이더라도 N이 50 밖에 되지 않아 상관이 없었네요. 
> 새로운 관점을 깨달을 수 있는 계기였습니다.
> [1주차] 브루트포스 BOJ_3085 제출_김범석

- src/main/java/changhyeon/BOJ_3085.java
문제를 여러 번 읽어보았는데 이해가 가지 않아 블로그 글 참고해서 진행했습니다.
1. 행을 기준으로 현재 위치와 다음 위치의 색상을 바꿔주기
2. 같은 색으로 이루어져있는 가장 긴 연속 부분을 골라 Max 값을 갱신한다.
3. 사탕을 모두 먹는다(= 변경된 위치를 다시 원 상태로 돌려놓는다)
4. 열도 마찬가지로 반복 한다.
- 시간복잡도: O(N^4) -> 위치 교환 중첩 for문 O(N^2) * 긴 연속 부분을 고른 다음 먹는 부분 중첩 for문 O(N^2)
- 공간복잡도: O(N^2) -> 2차원 배열을 이용하므로 O(N^2)
- 주어진 보드의 최고 크기 : 50
- 50^4 = 6,250,000
시간복잡도가 O(N^4) 이더라도 제한 시간 1초에 영향 없음
> [1주차] 브루트포스 BOJ_3085 제출_황창현

- src/main/java/charlesuu/BOJ_3085.java
장시간 문제가 풀리지 않아 블로그 참고했습니다.
배열을 순회하면서 가로 방향, 세로 방향으로 문자를 바꾼 뒤,
가로 방향, 세로 방향으로 전체 배열의 같은 사탕 최대 개수를 체크하는 방식입니다.
시간복잡도: O(N^4){가로 스왑, 배열 체크}  + O(N^4){세로 스왑, 배열 체크}
공간복잡도: O(N^2)
> [1주차] 브루트포스 BOJ_3085 제출_이현호

- src/main/java/changhyeon/BOJ_6064.java
1. 해를 N으로 나누었을 때 나머지 값으로 Y 값을 구할 수 있음.
2. 해는 M을 더하여 매번 X 값이 나올 수 있도록 고정 
3. M과 N의 최소 공배수까지만 위와 같은 작업을 할 수 있도록 구현
> [1주차] 브루트포스 BOJ_6064 제출_황창현

- .gitignore
- src/main/java/charlesuu/BOJ_6064.java
j를 N 으로 나머지 연산하기 전에 N = Y 인 경우/N !=Y 인 경우를 나누어서 풀이했습니다.
> [1주차] 브루트포스 BOJ_6064 이현호

- src/main/java/changhyeon/BOJ_1748.java
예를 들어 30을 찾는다고 했을 때
1의 자리는 총 30번,
10의 자리는 N - 9번 (1 ~ 9까지 제외)
100의 자리는 N - 99번 (1 ~ 99까지 제외)
....
이런식으로 증가하므로 N의 자리수를 초과하기 전까지 x 10씩하면서 -1을 빼어 매 자릿수마다 해당하는 값을 더하여 처리
> [1주차] 브루트포스 BOJ_1748 제출_황창현

- src/main/java/changhyeon/BOJ_14500.java
- [블로그 글](https://girawhale.tistory.com/35) 참고하여 풀었습니다.
- 추후 재 풀이 예정입니다.
> [1주차] 브루트포스 BOJ_14500 제출_황창현

- src/main/java/charlesuu/BOJ_15650.java
재귀함수를 이용하여 풀이했습니다. 순열과 비슷한 방식으로 풀이하였으며, 이전 단계에서 선택된 수보다 큰 값만 선택하는 방법으로 조합을 구현했습니다.
> [2주차] 브루트포스 BOJ_15650 제출_이현호

- src/main/java/changhyeon/BOJ_15651.java
- Sysout으로 처리했더니 시간초과나서 BufferedWriter로 변경해서 처리했습니다!
> [2주차] 브루트포스 BOJ_15651 제출_황창현

- src/main/java/tommy/BOJ_15650.java
기존 알고리즘에서 startNum 인자를 추가했습니다.
> [2주차] 브루트포스 BOJ_15650 제출_김범석

- src/main/java/charlesuu/BOJ_15651.java
순열 로직에서 이미 선택된 수를 제외하는 로직만 제거하여 구현했습니다.
> [2주차] 브루트포스 BOJ_15651 제출_이현호

- src/main/java/changhyeon/BOJ_18290.java
- 2차원 배열과 DFS를 이용해서 푸는 것이라는건 알았으나 어떻게 구현해야할지 몰라서 블로그 참고해서 구현했습니다.
- 막상 풀어보니 이전 N과M 문제와 굉장히 유사하네요!
- N과 M의 X, Y값을 혼동하여 계속 문제를 틀리고 있었습니다...
> [2주차] 브루트포스 BOJ_18290 황창현

- src/main/java/changhyeon/BOJ_1759.java
- 풀이를 정확히 이해하지 못하여 블로그 참고해서 풀었습니다!
- 추후 재풀이 예정입니다.
> [2주차] 브루트포스 BOJ_1759 황창현

- src/main/java/changhyeon/BOJ_14889.java
1. 우선 입력받은 N 값을 재귀로 팀을 나눈다.
2. 팀이 나뉘었을 때 각 팀의 모든 경우의 수를 구하여 능력치 점수를 계산하고 MIN 값을 정한다.
> [2주차] 브루트포스 BOJ_14889 제출_황창현

- src/main/java/changhyeon/BOJ_2529.java
1. 우선 재귀로 모든 숫자를 만듭니다.
2. 숫자를 만들 때 마다 부등호에 대입하여 정상적으로 식이 성립하면 List에 저장합니다.
3. 저장된 리스트에서 제일 마지막과 첫번째 요소를 출력합니다.
Commit Message 2주차 -> 3주차 입니다..!
> [3주차] 브루트포스 BOJ_2529 제출_황창현

- src/main/java/tommy/BOJ_10972.java
순열 문제는 처음이라 블로그를 참고해서 작성했습니다. 
블로그에 설명이 잘 되어 있어서 같이 올려요 
[참고 블로그](https://sskl660.tistory.com/54)
> [3주차] 브루트포스 BOJ_10972 김범석

- src/main/java/changhyeon/BOJ_10974.java
> [3주차] 브루트포스 BOJ_10974 제출_황창현

- src/main/java/changhyeon/BOJ_10971.java
- 문제의 내용이 잘 이해가 가지 않아 블로그 글 참고해서 풀었습니다!
1. 출발 도시가 한정되어있지 않고 모든 곳에서 출발이 가능하기 때문에 시작할 때부터 for문으로 N의 값만큼 돌면서 출발지를 계속 변경시켰습니다.
2. 재귀 호출시 아래와 같은 매개변수를 이용해서 처리했습니다.
- `출발 도시(start)`: 출발 도시가 어디인지 마지막 계산에서 편하게 이용하기 위해 사용
- `이전 도시(prev)`: 이전 도시가 어디인지 알고 있어야 이전도시 -> 현재 도시의 비용을 구할 수 있기 때문에 사용
- `이동 횟수(depth)`: 현재 몇개의 도시를 이동했는지 파악하여 중간에 계산할 수 있도록 함
- `합산 금액(sum)`: 모든 도시를 방문하고 돌아왔을 때의 비용을 갱신하기 위함
> [3주차] 브루트포스 BOJ_10971 황창현

- src/main/java/changhyeon/BOJ_11723.java
- 처음에 List로 만들어서 풀었는데 시간초과 나서 비트마스크로 풀었습니다.
(시간초과 뜬 이유가 리스트를 사용해서가 아닌 출력문 때문이었습니다..)
> [3주차] 브루트포스 BOJ_11723 제출_황창현

- src/main/java/charlesuu/BOJ_11723.java
비트 마스킹 개념 이해가 부족해서 블로그 보면서 풀이했습니다.
풀고 나니 조금 알 것 같기도 한데 복습 잘 해봐야겠네요ㅎㅎ
> [4주차] 브루트포스 BOJ_11723 제출_이현호

- src/main/java/changhyeon/BOJ_1182.java
답은 정상적으로 나오나 효율적이지 못한 방법으로 풀어서 시간초과가 납니다!
답안 보고 재풀이 예정입니다.
> [4주차] 브루트포스 BOJ_1182 제출_황창현

- src/main/java/changhyeon/BOJ_11727.java
> [4주차] DP BOJ_11727 제출_황창현

- src/main/java/changhyeon/BOJ_15990.java
- 블로그 보면서 참고해서 풀었습니다.
- 추후 재풀이 예정입니다.
T의 값에 따라 1로 끝나는 것, 2로 끝나는 것, 3으로 끝나는 경우의 수를 계산해서 이차원 배열로 처리
> [4주차] DP BOJ_15990 제출_황창현

- src/main/java/changhyeon/BOJ_1699.java
> [5주차] DP BOJ_1699 제출_황창현

- src/main/java/charlesuu/BOJ_15988.java
- src/main/java/charlesuu/BOJ_1699.java
안 풀려서 블로그 찾아보고 풀었습니다.
오늘 재풀이 해볼 생각입니다.
> [5주차] DP BOJ_1699, 15988 제출_이현호

- src/main/java/charlesuu/BOJ_16935.java
- src/main/java/charlesuu/BOJ_2178.java
- src/main/java/charlesuu/BOJ_7562.java
- src/main/java/charlesuu/BOJ_7576.java
16935, 2178, 7576 제출
7562 재풀이입니다~
> [6주차 BFS] BOJ_16935, BOJ_2178, 7576제출, 7562 재풀이_이현호

- src/main/java/changhyeon/BOJ_16931.java
- src/main/java/changhyeon/BOJ_2290.java
**2290번 문제**
- 어떻게 구현해야할지 모르겠어서 인터넷 참고해서 풀었습니다.
- 이슈에 재풀이 등록해두었고 나중에 다시 풀어볼 예정입니다~
> [8주차] 시뮬레이션과 구현 BOJ_2290, BOJ_16931 제출_황창현
